model_details:
  model_id: MobileNet
  model_class: MobileNet_class
  model_tags: [CNN]
  suitable_datasets: [CIFAR-10]

default_training_config:
  use_custom_dataloader: False
  custom_loader_args: None

  use_custom_trainer: False
  custom_trainer_args: None

  use_custom_validator: False
  custom_validator_args: None

  model_args:
    num_classes: 10
